image: "swift:5.3-focal"

stages:
  - build-libs
  - test-libs
  - build-exes
  - test-exes

cache:
  paths:
    - "*/.build"

distributed-chat:build:
  stage: build-libs
  script:
    - (cd DistributedChatKit && swift build)

distributed-chat:test:
  stage: test-libs
  script:
    - (cd DistributedChatKit && swift test)
  needs:
    - distributed-chat:build

simulation-protocol:build:
  stage: build-libs
  script:
    - (cd DistributedChatSimulationProtocol && swift build)

cli:build:
  stage: build-exes
  script:
    - (cd DistributedChatCLI && swift build)
  needs:
    - distributed-chat:build
    - simulation-protocol:build

simulation-server:build:
  stage: build-exes
  script:
    - (cd DistributedChatSimulationServer && swift build)
  needs:
    - simulation-protocol:build

simulation-server:test:
  stage: test-exes
  script:
    - (cd DistributedChatSimulationServer && swift test)
  needs:
    - simulation-server:build

app:build:
  stage: build-exes
  rules:
    - when: never # TODO: Reenable
  tags:
    - macos
  script:
    - xcodebuild build -scheme DistributedChatApp -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=14.3"
  needs:
    - distributed-chat:build
