name: CLI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ['5.7']
    
    steps:
    - uses: actions/checkout@v3
    - uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build
      working-directory: DistributedChatCLI
